In [15]:
import numpy as np 

arr=np.array([3,4,5,6])
arr2d=np.array([[[1,2,3,4],[6,7,8,9,]],[[4,5,6,7],[6,7,8,9]]])
print(arr)
print(arr2d)
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.size)
print(arr2d.dtype)

[3 4 5 6]
[[[1 2 3 4]
  [6 7 8 9]]

 [[4 5 6 7]
  [6 7 8 9]]]
3
(2, 2, 4)
16
int32


In [33]:
#array creation
a=np.zeros(5)
print(a)
b=np.ones((2,3))
print(b)
arrange=np.arange(0,20,3)
print(arrange)

line=np.linspace(0,1,6)
print(line)

rand=np.random.rand(5)
print(rand)
mat=np.random.rand(3,3)
print(mat)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 0  3  6  9 12 15 18]
[0.  0.2 0.4 0.6 0.8 1. ]
[0.37417116 0.28020627 0.59290045 0.09507886 0.39580052]
[[0.31642991 0.94420351 0.94517967]
 [0.36148111 0.37102154 0.22538595]
 [0.26312908 0.95556152 0.3850527 ]]


In [34]:
#NumPy Small Practical Quiz
#Q1.Create a 1D NumPy array of 7 zeros. Which function will you use?

q1=np.zeros(7)
print(q1)


[0. 0. 0. 0. 0. 0. 0.]


In [35]:
#You want to create 5 numbers evenly spaced between 10 and 20. Which function will you use?
sep=np.linspace(10,20,5)
print(sep)

[10.  12.5 15.  17.5 20. ]


In [37]:
#Q4.Create a 2x4 array filled with random decimal numbers between 0 and 1.
arr=np.random.rand(2,4)
print(arr)

[[0.71829665 0.28176361 0.13875968 0.34228084]
 [0.87421953 0.1889903  0.11927434 0.53555269]]


In [62]:
#Q5.How would you create an array of 6 random integers between 50 and 100?
ran=np.random.randint(50,100,6)
print(ran)

[90 88 75 88 51 86]


In [63]:
#array operation
mean=np.mean(ran)
print(mean)

sum=np.sum(ran)
print(sum)

std=np.std(ran)
print(std)

max=np.max(ran)
print(max)

79.66666666666667
478
13.719410418171117
90


In [64]:
#reshaping and resizing

res=ran.reshape(2,3)
print(res)

flat=res.ravel()
print(flat)

tran=res.transpose()
print(tran)

resiz=res.resize(3,2)
print(resiz)

[[90 88 75]
 [88 51 86]]
[90 88 75 88 51 86]
[[90 88]
 [88 51]
 [75 86]]
None


In [92]:
#arrayconcentation and splitting
art=np.random.randint(1,8,4)
b=np.random.randint(1,8,4)

print(np.concatenate((art,b)))


split=np.split(art,b)
print(split)

[6 7 3 1 5 2 4 6]
[array([6, 7, 3, 1]), array([], dtype=int32), array([3, 1]), array([], dtype=int32), array([], dtype=int32)]


In [106]:
#usefullfunction

print(np.unique(art))
print(np.sort(b))


where=np.random.randint(10,50,5)
print(where)
print(np.where(where > 25,1,0))

b=np.copy(where)
b[0]=50
print(b)

[1 3 6 7]
[2 4 5 6]
[13 48 17 33 42]
[0 1 0 1 1]
[50 48 17 33 42]


In [117]:
#Easy Level
#Create an array of numbers from 0 to 10.

e=np.random.randint(0,10,6)

print(np.array(e))


#Create a 3x3 matrix filled with ones.
print(np.ones((3,3)))

#Find the maximum and minimum value in the array [4, 7, 1, 9, 12].'
print(np.max((4,7,1,9,12)))
print(np.max(e))

#Create an array of 10 random integers between 1 and 100.
print(np.random.randint(0,100,10))

#Find unique elements in the array [1, 2, 2, 3, 4, 4, 5].
print(np.unique((1,2,2,3,4,4,5)))

[2 5 0 5 0 1]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
12
5
[99 39 24 82 33 68 38 29 59 76]
[1 2 3 4 5]


In [175]:
#medium level
#Reshape a 1D array of 9 elements into a 3x3 matrix.

m=np.random.randint(0,50,9)

print(m.reshape(3,3))

#Select all even numbers from an array [5, 6, 7, 8, 9, 10].
print("even number",m[m%2==0])

#Sort the array [8, 3, 1, 5, 9] in ascending order.
print(np.sort(m))

#Split the array [1,2,3,4,5,6,7,8,9] into 3 equal parts.
print(np.split(m,3))

#Stack two arrays [1,2,3] and [4,5,6] vertically.
print(np.vstack(m))

[[48 20 39]
 [33 34  5]
 [ 3 14 34]]
even number [48 20 34 14 34]
[ 3  5 14 20 33 34 34 39 48]
[array([48, 20, 39]), array([33, 34,  5]), array([ 3, 14, 34])]
[[48]
 [20]
 [39]
 [33]
 [34]
 [ 5]
 [ 3]
 [14]
 [34]]


In [179]:
#hardlevel

h=np.random.randint(0,50,25)
#Replace all values greater than 10 in an array with 10.
print(np.where(h>10,10,1))

#Create a 5x5 matrix with random numbers and find the mean of each row.
a=np.random.rand(5,5)
print(np.mean(a))

#Transpose a 4x3 random matrix.
arr=np.random.rand(4,3)

transpose=arr.T #.t is shorcutr for transpose
print(transpose)


#Broadcast an array of shape (3,) to a matrix of shape (3, 3).
sha=np.random.rand(3,3)
print(sha)

#Given a 2D matrix, find the sum of the diagonal elements.
f=np.random.rand(3,3)
print(f)
print(np.trace(f))

[10  1 10  1 10 10 10 10 10 10 10 10 10 10 10 10  1 10 10 10 10  1 10 10
  1]
0.40667628486411894
[[0.57138118 0.4540497  0.47971519 0.37271876]
 [0.08713456 0.44327703 0.94768569 0.07888351]
 [0.29083456 0.54192318 0.57652995 0.18181448]]
[[0.95096941 0.0894482  0.95806661]
 [0.26886839 0.02344682 0.520732  ]
 [0.15328233 0.10803456 0.40133418]]
[[0.96165852 0.84261554 0.16951905]
 [0.49415387 0.67580246 0.91298393]
 [0.61166944 0.89992453 0.29827595]]
1.9357369295601976


In [186]:
matrix=np.ones((6,6))


matrix[1:-1,1:-1] =0
print(matrix)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
